version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ./src/:/src
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - default
  php:
    build:
      context: .
      dockerfile: ./image/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    env_file:
      - .env
    volumes:
      - ./src:/src
    networks:
      - default
    links:
      - database
      - redis
  node:
    image: node:13
    volumes:
      - ./src:/src
    networks:
      - default
    working_dir: /src
  database:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
  redis:
    image: redis:5.0.8-alpine
    ports:
      - ${REDIS_EXTERNAL_PORT}:6379
    volumes:
      - redis-data:/data
    networks:
      - default

volumes:
  mysql-data:
  redis-data:

networks:
  default:
    driver: bridge